import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    /*boton: {
        backgroundColor: "#5865F2",
        padding: 10,
        marginLeft: 10,
        marginRight: 10,
        marginTop: 20,
        borderRadius: 5,
    }*/
    textoB: {
        color: "#fff",
        fontSize: 15,
        fontWeight: "bold",
        textAlign: "center",
    },
    container: {
        flex: 1,
        backgroundColor: "#000000",
        alignItems: "strech",
        justifyContent: "center",
        padding: 10,
    },
    encabezado: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        paddingTop: 20,
    },
    cuerpo: {
        flex: 12,
        backgroundColor: '#000',
    },
    pie: {
        flex: 2,
        justifyContent: "start",
        flexDirection: "row",
        backgroundColor: "#000000",
        padding: 20,
    },
    textF: {
        fontSize: 23,
        fontWeight: "bold",
        textAlign: "center",
        marginTop: 8,
        marginLeft: 20,
        marginRight: 20,
        color: "#fff",
    },
    textL: {
        fontSize: 12,
        fontWeight: "bold",
        textAlign: "center",
        marginTop: 10,
        marginLeft: 20,
        marginRight: 20,
        color: "#A0A0A0",
    },
    textL2: {
        fontSize: 12,
        fontWeight: "bold",
        marginTop: 20,
        marginLeft: 10,
        marginBottom: 10,
        color: "#A0A0A0",
    },
    images: {
        resizeMode: "cover",
        width: 40,
        height: 40,
    },
    link: {
        fontSize: 12,
        marginLeft: 10,
        marginTop: 5,
        fontWeight: "bold",
        color: "#3D8CB5",
    },
    inputs: {
        backgroundColor: "#32323C",
        marginBottom: 10,
        marginTop: 2,
        marginLeft: 10,
        marginRight: 10,
        height: 48,
        borderRadius: 5,
        fontSize: 15,
        padding: 15,
        color: "#fff",
        fontWeight: "bold",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
    },
    input: {
        color: "#fff",
        width: 280,
        fontWeight: "bold",
    },
    icon: {
        marginLeft: 10,
    },
    container2: {
        paddingRight: 5,
        paddingLeft: 5,
        marginTop: 60,
        width: '100%',
        height: '100%',
        alignItems: 'center',
    },
    container: {
        width: '100%',
        height: '100%',
    },
    result: {
        marginLeft: 5,
        marginRight: 5,
        padding: 10,
        height: 70,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: 'flex-end',
        backgroundColor: '#3b3a3a',
    },
    resultText: {
        color: '#ffffff',
        fontSize: 30,
        fontWeight: "bold",
    },
    buttons: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 30,
        gap: 3,
        justifyContent: 'center',
        alignItems: 'center',
    },
    button: {
        width: '23%',
        aspectRatio: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "#3498db",
        borderRadius: 10,
        margin: 2,
    },
    buttonText: {
        color: '#ffffff',
        fontSize: 20,
    },
});

